### PR TITLE
Copy lesson over

### PR DESCRIPTION
**Pull request by kcleland0818**
This lesson was just copied over from what is originally in Java Mod 1

### CODE REVIEW

**Review by linda-seiter — COMMENTED** [review]
It might be better to move this lesson after conditionals or loops are introduced,
since they can't really apply these concepts.

**Review by developerjaym — APPROVED** [review]

**Review by linda-seiter — APPROVED** [review]
The Runestone Academy link takes you to a login page

**Comment by kcleland0818** [comment]
> The Runestone Academy link takes you to a login page

@linda-seiter 

When you click on it, you don't see this page?

image

**Comment by linda-seiter** [comment]
> > The Runestone Academy link takes you to a login page
> 
> @linda-seiter
> 
> When you click on it, you don't see this page?
> 
> image

No I see a login page 
https://runestone.academy/user/login?_next=/courses%3Fcurrent_course%3DCS128Seiter%26requested_course%3Dapcsareview.

**Comment by kcleland0818** [comment]
> > > The Runestone Academy link takes you to a login page
> > 
> > 
> > @linda-seiter
> > When you click on it, you don't see this page?
> > image
> 
> No I see a login page https://runestone.academy/user/login?_next=/courses%3Fcurrent_course%3DCS128Seiter%26requested_course%3Dapcsareview.

That's really weird because I don't even have an account with runstone academy! I'll remove the link. I really just couldn't remember De Morgan's first name and thought it was a good a reference (the page where I took the screenshot originally). The YouTube and O'Reilly book have decent definitions though explaining how it works.

**Review by linda-seiter — APPROVED** [review]

**Pull request merged**
